### ISSUE TITLE
../include.mk: No such file or directory

### ISSUE THREAD

**Issue by kilianc** [tonyg/presence-exchange#1]
```
Makefile:5: ../include.mk: No such file or directory
make: *** No rule to make target `../include.mk'.  Stop.
```

**Comment by tonyg** [comment]
It needs the rabbitmq-umbrella from https://github.com/rabbitmq/rabbitmq-public-umbrella, but further will need quite a bit of dusting-off before it will build, would be my guess. The build setup has changed a lot over the last year or so. Also I think the pluggable-exchange model is no longer what it once was, so the code itself will probably have to change.

**Comment by majek** [comment]
Tony, are you still planning on pulling back [my fork](https://github.com/majek/rabbitmq-x-presence/)?

**Comment by tonyg** [comment]
Yes, that's been on my todo list for a while. ... OK, let's see if I can't get it done in half an hour.

**Comment by tonyg** [comment]
OK, so that wasn't a half-hour, but the code is mostly working now. There's one failing test. Also, Marek, I changed the behaviour slightly to drop messages as previously. I'll write an explanation of why in the README.

**Comment by majek** [comment]
Well done! And tested! Cool, really cool. I'm sure I had a reason to change semantics, but I forgot what it was. It would be nice to hear why you have strong feelings about it - and understand the differences.

BTW, I also wrote few tests long time ago, but in a way less structured manner, but it's probably irrelevant now: https://github.com/majek/dump/blob/master/puka/test-presence-exchange.py
