### ISSUE TITLE
Doesn't work on latest rabbit build

### ISSUE THREAD

**Issue by marksteele** [tonyg/presence-exchange#2]
diff --git a/src/presence_exchange.erl b/src/presence_exchange.erl
index e7ef45f..03bfa52 100644
--- a/src/presence_exchange.erl
+++ b/src/presence_exchange.erl
@@ -18,7 +18,7 @@
                     {enables,     kernel_ready}]}).

 -export([description/0, serialise_events/0, route/2]).
--export([validate/1, create/2, recover/2, delete/3, add_binding/3,
+-export([validate/1, validate_binding/2, create/2, recover/2, delete/3, add_binding/3,
         remove_bindings/3, assert_args_equivalence/2]).

 encode_binding_delivery(DeliveryXName,
@@ -46,6 +46,7 @@ route(_Exchange, _Delivery) ->
     [].

 validate(_X) -> ok.
+validate_binding(_X, _B) -> ok.
 create(_Tx, _X) -> ok.
 recover(_X, _Bs) -> ok.
 delete(_Tx, _X, _Bs) -> ok.

**Comment by tonyg** [comment]
Thanks for the patch - I've applied something similar, and things seem to be working OK. Please let me know if things are still busted.
