### ISSUE TITLE
Interaction with rabbitmq_server-3.5.0

### ISSUE THREAD

**Issue by vdeters** [tonyg/presence-exchange#7]
More of a question than an issue at this point. Running rabbit_presence_exchange-3.3.0-20140418.ez with rabbitmq_server-3.4.4 works fine, but using the same presence exchange plugin with rabbitmq_server-3.5.0 throws this:

server exception, the broker returned server connection error 541, message: INTERNAL_ERROR

when the client binds a queue to the presence exchange with a non-empty string to generate presence events.

Not sure if we just need to try a rebuilt presence exchange - any chance of getting a 3.5.0 prebuilt binary?

Thanks,
Vince

**Comment by tonyg** [comment]
Hi Vince,

It sounds like something about the (undocumented) plugin API might have changed again; if that's the case, it may not be quite as simple as rebuilding the code. Could you post the error messages from the server logs corresponding to the INTERNAL_ERROR you see, please? It'd give me a quick start on fixing the issue.

Tony

**Comment by vdeters** [comment]
Thanks Tony. Below is output from the two server logs I see.
Vince

rabbit@trcv001.log:

=INFO REPORT==== 21-Apr-2015::11:38:32 ===
accepting AMQP connection <0.7819.0> (10.40.14.159:39179 ->
192.168.9.85:5672)

=INFO REPORT==== 21-Apr-2015::11:38:32 ===
accepting AMQP connection <0.7828.0> (10.40.14.159:39180 ->
192.168.9.85:5672)

=INFO REPORT==== 21-Apr-2015::11:38:32 ===
accepting AMQP connection <0.7842.0> (10.40.14.159:39181 ->
192.168.9.85:5672)

=ERROR REPORT==== 21-Apr-2015::11:38:32 ===
*\* Generic server <0.7848.0> terminating
*\* Last message in was {'$gen_cast',
                           {method,
                               {'queue.bind',0,
                                   <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>,
                                   <<"ESP_failoverpresence">>,

 <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>,false,
                                   []},
                               none,noflow}}
*\* When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.7842.0>,
                            <0.7846.0>,<0.7842.0>,
                            <<"10.40.14.159:39181 -> 192.168.9.85:5672">>,
                            {lstate,<0.7847.0>,false},
                            none,1,
                            {[],[]},
                            {user,<<"guest">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                            <<"/">>,<<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>,
                            {dict,0,16,16,8,80,48,

{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {state,
                                {dict,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},

{{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}},
                                erlang},
                            {dict,0,16,16,8,80,48,

{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {dict,0,16,16,8,80,48,

{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {set,0,16,16,8,80,48,

{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            <0.7843.0>,
                            {state,none,5000,undefined},
                            false,1,
                            {{0,nil},{0,nil}},
                            [],
                            {{0,nil},{0,nil}},
                            [],none,0,none}
*\* Reason for termination ==
*\* {function_clause,
       [{presence_exchange,deliver,
            [{delivery,false,false,<0.7848.0>,
                 {basic_message,
                     {resource,<<"/">>,exchange,<<"ESP_failoverpresence">>},
                     [<<>>],
                     {content,60,
                         {'P_basic',undefined,undefined,
                             [{<<"action">>,longstr,<<"bind">>},
                              {<<"exchange">>,longstr,
                               <<"ESP_failoverpresence">>},
                              {<<"queue">>,longstr,
                               <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                              {<<"key">>,longstr,
                               <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>}],
                             undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined},
                         none,none,
                         [<<>>]},

 <<33,61,37,249,78,250,199,110,132,204,184,19,32,229,94,212>>,
                     false},
                 undefined,noflow}],
            []},
        {presence_exchange,add_binding,3,[]},
        {rabbit_binding,x_callback,4,[]},
        {rabbit_binding,'-add/3-fun-0-',3,[]},
        {rabbit_channel,binding_action,9,[]},
        {rabbit_channel,handle_cast,2,[]},
        {gen_server2,handle_msg,2,[]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

=ERROR REPORT==== 21-Apr-2015::11:38:32 ===
Error on AMQP connection <0.7842.0> (10.40.14.159:39181 -> 192.168.9.85:5672,
vhost: '/', user: 'guest', state: running), channel 1:
{function_clause,
    [{presence_exchange,deliver,
         [{delivery,false,false,<0.7848.0>,
              {basic_message,
                  {resource,<<"/">>,exchange,<<"ESP_failoverpresence">>},
                  [<<>>],
                  {content,60,
                      {'P_basic',undefined,undefined,
                          [{<<"action">>,longstr,<<"bind">>},

 {<<"exchange">>,longstr,<<"ESP_failoverpresence">>},
                           {<<"queue">>,longstr,
                            <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                           {<<"key">>,longstr,
                            <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>}],
                          undefined,undefined,undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,undefined,
                          undefined},
                      none,none,
                      [<<>>]},

<<33,61,37,249,78,250,199,110,132,204,184,19,32,229,94,212>>,
                  false},
              undefined,noflow}],
         []},
     {presence_exchange,add_binding,3,[]},
     {rabbit_binding,x_callback,4,[]},
     {rabbit_binding,'-add/3-fun-0-',3,[]},
     {rabbit_channel,binding_action,9,[]},
     {rabbit_channel,handle_cast,2,[]},
     {gen_server2,handle_msg,2,[]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

=WARNING REPORT==== 21-Apr-2015::11:38:32 ===
Non-AMQP exit reason '{function_clause,
                       [{presence_exchange,deliver,
                         [{delivery,false,false,<0.7848.0>,
                           {basic_message,
                            {resource,<<"/">>,exchange,
                             <<"ESP_failoverpresence">>},
                            [<<>>],
                            {content,60,
                             {'P_basic',undefined,undefined,
                              [{<<"action">>,longstr,<<"bind">>},
                               {<<"exchange">>,longstr,
                                <<"ESP_failoverpresence">>},
                               {<<"queue">>,longstr,
                                <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                               {<<"key">>,longstr,
                                <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>}],
                              undefined,undefined,undefined,undefined,
                              undefined,undefined,undefined,undefined,
                              undefined,undefined,undefined},
                             none,none,
                             [<<>>]},
                            <<33,61,37,249,78,250,199,110,132,204,184,19,32,
                              229,94,212>>,
                            false},
                           undefined,noflow}],
                         []},
                        {presence_exchange,add_binding,3,[]},
                        {rabbit_binding,x_callback,4,[]},
                        {rabbit_binding,'-add/3-fun-0-',3,[]},
                        {rabbit_channel,binding_action,9,[]},
                        {rabbit_channel,handle_cast,2,[]},
                        {gen_server2,handle_msg,2,[]},
                        {proc_lib,init_p_do_apply,3,
                         [{file,"proc_lib.erl"},{line,237}]}]}'

=INFO REPORT==== 21-Apr-2015::11:38:33 ===
accepting AMQP connection <0.7857.0> (10.40.14.159:39182 ->
192.168.9.85:5672)

=INFO REPORT==== 21-Apr-2015::11:38:33 ===
accepting AMQP connection <0.7871.0> (10.40.14.159:39183 ->
192.168.9.85:5672)

=INFO REPORT==== 21-Apr-2015::11:38:33 ===
accepting AMQP connection <0.7880.0> (10.40.14.159:39184 ->
192.168.9.85:5672)

=INFO REPORT==== 21-Apr-2015::11:39:02 ===
closing AMQP connection <0.7842.0> (10.40.14.159:39181 -> 192.168.9.85:5672)

rabbit@trcv001-sasl.log:

=CRASH REPORT==== 21-Apr-2015::11:38:32 ===
  crasher:
    initial call: gen:init_it/6
    pid: <0.7848.0>
    registered_name: []
    exception exit: {function_clause,
                     [{presence_exchange,deliver,
                       [{delivery,false,false,<0.7848.0>,
                         {basic_message,
                          {resource,<<"/">>,exchange,
                           <<"ESP_failoverpresence">>},
                          [<<>>],
                          {content,60,
                           {'P_basic',undefined,undefined,
                            [{<<"action">>,longstr,<<"bind">>},
                             {<<"exchange">>,longstr,
                              <<"ESP_failoverpresence">>},
                             {<<"queue">>,longstr,
                              <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                             {<<"key">>,longstr,
                              <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>}],

undefined,undefined,undefined,undefined,undefined,

undefined,undefined,undefined,undefined,undefined,
                            undefined},
                           none,none,
                           [<<>>]},

<<33,61,37,249,78,250,199,110,132,204,184,19,32,229,
                            94,212>>,
                          false},
                         undefined,noflow}],
                       []},
                      {presence_exchange,add_binding,3,[]},
                      {rabbit_binding,x_callback,4,[]},
                      {rabbit_binding,'-add/3-fun-0-',3,[]},
                      {rabbit_channel,binding_action,9,[]},
                      {rabbit_channel,handle_cast,2,[]},
                      {gen_server2,handle_msg,2,[]},
                      {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,237}]}]}
      in function  gen_server2:terminate/3
    ancestors: [<0.7845.0>,<0.7844.0>,<0.7841.0>,<0.7840.0>,
                  rabbit_tcp_client_sup,rabbit_sup,<0.93.0>]
    messages: []
    links: [<0.7845.0>]
    dictionary: [{guid_secure,{{1,rabbit@trcv001,#Ref<0.0.1.140712>},0}},
                  {{xtype_to_module,'x-presence'},presence_exchange},
                  {process_name,
                      {rabbit_channel,
                          {<<"10.40.14.159:39181 -> 192.168.9.85:5672
">>,1}}},
                  {permission_cache,

[{{resource,<<"/">>,exchange,<<"ESP_failoverpresence">>},
                        read},
                       {{resource,<<"/">>,queue,
                            <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                        write},
                       {{resource,<<"/">>,queue,
                            <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                        configure},

 {{resource,<<"/">>,exchange,<<"ESP_failoverpresence">>},
                        configure}]},
                  {guid,{{557655545,1325057902,2228008979,551902932},1}}]
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 3914
  neighbours:

=SUPERVISOR REPORT==== 21-Apr-2015::11:38:32 ===
     Supervisor: {<0.7845.0>,rabbit_channel_sup}
     Context:    child_terminated
     Reason:     {function_clause,
                  [{presence_exchange,deliver,
                    [{delivery,false,false,<0.7848.0>,
                      {basic_message,

 {resource,<<"/">>,exchange,<<"ESP_failoverpresence">>},
                       [<<>>],
                       {content,60,
                        {'P_basic',undefined,undefined,
                         [{<<"action">>,longstr,<<"bind">>},

{<<"exchange">>,longstr,<<"ESP_failoverpresence">>},
                          {<<"queue">>,longstr,
                           <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>},
                          {<<"key">>,longstr,
                           <<"amq.gen-O_bA-sZBfZlAPTl0NVJGHQ">>}],
                         undefined,undefined,undefined,undefined,undefined,
                         undefined,undefined,undefined,undefined,undefined,
                         undefined},
                        none,none,
                        [<<>>]},

 <<33,61,37,249,78,250,199,110,132,204,184,19,32,229,94,
                         212>>,
                       false},
                      undefined,noflow}],
                    []},
                   {presence_exchange,add_binding,3,[]},
                   {rabbit_binding,x_callback,4,[]},
                   {rabbit_binding,'-add/3-fun-0-',3,[]},
                   {rabbit_channel,binding_action,9,[]},
                   {rabbit_channel,handle_cast,2,[]},
                   {gen_server2,handle_msg,2,[]},
                   {proc_lib,init_p_do_apply,3,
                    [{file,"proc_lib.erl"},{line,237}]}]}
     Offender:   [{pid,<0.7848.0>},
                  {name,channel},
                  {mfargs,
                      {rabbit_channel,start_link,
                          [1,<0.7842.0>,<0.7846.0>,<0.7842.0>,
                           <<"10.40.14.159:39181 -> 192.168.9.85:5672">>,
                           rabbit_framing_amqp_0_9_1,
                           {user,<<"guest">>,
                               [administrator],
                               [{rabbit_auth_backend_internal,none}]},
                           <<"/">>,[],<0.7843.0>,<0.7847.0>]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]

=SUPERVISOR REPORT==== 21-Apr-2015::11:38:32 ===
     Supervisor: {<0.7845.0>,rabbit_channel_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.7848.0>},
                  {name,channel},
                  {mfargs,
                      {rabbit_channel,start_link,
                          [1,<0.7842.0>,<0.7846.0>,<0.7842.0>,
                           <<"10.40.14.159:39181 -> 192.168.9.85:5672">>,
                           rabbit_framing_amqp_0_9_1,
                           {user,<<"guest">>,
                               [administrator],
                               [{rabbit_auth_backend_internal,none}]},
                           <<"/">>,[],<0.7843.0>,<0.7847.0>]}},
                  {restart_type,intrinsic},
                  {shutdown,4294967295},
                  {child_type,worker}]

**Comment by kporembinski** [comment]
I have tested on Red Hat 6.6 and the same results I have.

**Comment by tonyg** [comment]
Rebuilding the plugin and running the tests shows no obvious problems, so it could be that a simple rebuild makes the problem go away. I've released new binary builds of the presence- and udp-exchanges at http://www.eighty-twenty.org/tech/rabbitmq/binary-plugins.html, so please grab them, try them out, and let me know if they fix your issues. Thanks!

**Comment by vdeters** [comment]
Excellent, thanks Tony. I'll let you know the results.
Vince

**Comment by vdeters** [comment]
That appears to have fixed it. We tried your new presence exchange with
server 3.5.0 and 3.5.1 and it worked with both. Thanks for your help,
Vince

**Comment by tonyg** [comment]
Great, thanks. Good to know it works.
